### PR TITLE
Update dialog icon for GTK3

### PR DESCRIPTION
**Pull request by snoopy**
TA now uses GTK3 which has a different option for dialog icons.

### CODE REVIEW

**Comment by rgieseke** [comment]
With this change, there is no symbol for me, on Linux? Which platform are you testing this on?

**Comment by rgieseke** [comment]
Might be related: https://github.com/orbitalquark/textadept/discussions/178#discussioncomment-2346099

Maybe i need to re-compile and re-download all dependencies ...

**Comment by snoopy** [comment]
On Windows 10 there will be some sort of default icon when using the gtk prefix. On Linux the icon seems to work fine either way as described by Mitchell.  
The documentation for TA now seems to use the version without prefix: https://orbitalquark.github.io/textadept/api.html#ui.dialogs

**Comment by rgieseke** [comment]
Thanks! I think maybe on Windows and macOS the GTK things are only what's packaged with Textadept, maybe on Linux it's more lenient.

**Comment by rgieseke** [comment]
With the nightly build it works fine, so it was something with my local build.

**Pull request merged**
