### PR TITLE
Fix save_buffer_as

### PR DESCRIPTION
**Pull request by loomer**
The old function would save an arbitrary buffer instead of the current one. 
Also changed the overwrite confirmation to be more apparent.

Could you have a look and let me know if you find any errors?

### CODE REVIEW

**Comment by loomer** [comment]
This will now always pop up a window asking the user for a filename. A filename will always be preselected. 
Consider the case where the user wants to save a file as "foo" but a file named "foobar" already exists. In this case the input box will have foo_bar preselected but the user can change it to "foo" or simply press OK to overwrite the existing file.

**Comment by rgieseke** [comment]
Nice, thanks! I will need to try this out a bit more ...

**Comment by rgieseke** [comment]
Using this more ... what do you think, should it maybe display the full path in the final conformation box?

**Comment by rgieseke** [comment]
Good points, display only would certainly be the right thing to do ...
On the other issue, this is probably why i ended up removing the save as functionality and just using the built-in dialogue. Not sure what to do ...If there is a "native" dialogue popping up anyway, one could as well use the native one ...

**Comment by rgieseke** [comment]
>  I'll look into mitigating the directory issue. It doesn't happen that often, at least in my experience.

Awesome!

**Comment by rgieseke** [comment]
Since it's possible to overwrite files inadvertently with the `save as` dialogue i'm quite reluctant to include something that differs from the "default" system dialogue as it might confuse users.
Maybe it's something for a separate plug-in? I'd likely use it myself.

**Comment by loomer** [comment]
Good point. I changed things around to make this (hopefully) impossible to happen.
Now the overwrite check is a simple messagebox to be more in line with other TA dialogs. The check also gets invoked when forcing the save.

**Comment by loomer** [comment]
Have you had a chance to review the changed version yet?

**Comment by rgieseke** [comment]
Not really - i'm leaning on having this as an external plugin. I think it's better to keep Textredux core to text-only interfaces.
For a 'save as' dialogue it should work as the system dialogue.

We should have a section in the Readme with links to plugins - you have quite a few ...

**Comment by loomer** [comment]
Not sure I follow the reasoning but I don't mind. As you aptly observed I have too many modules already so I won't make this into another one but rather keep it as a patch.

Regarding a plugin/module section I don't think it makes sense as this doesn't really have enough reach. If anyone wants more exposure for their module(s) they could always ask Mitchell to put it on the wiki.
If however you do decide to make a section anways I'd kindly ask not to be included as I don't think my modules are production-ready. I only keep them on GH to have an easy way to deploy them when I set up TA on a new machine.

Cheers.

**Comment by loomer** [comment]
Didn't see you already included the list, sorry about that.
As I explained above I'd rather not be part of it. I'm sure there are other modules you can mention however.

**Comment by rgieseke** [comment]
Reverted, sorry for the premature inclusion. At the moment i don't feel comfortable including and maintaining this, as it breaks the text-only interface Textredux provides and i personally probably won't use it (if i have to pop up a GUI dialogue i can use the default GUI dialogue)

Thanks again for your contribution(s)!

**Comment by loomer** [comment]
>(if i have to pop up a GUI dialogue i can use the default GUI dialogue)

I still don't follow. Maybe I just explained it poorly but there is no GUI popping out anywhere. The selection is done entirely within the TR interface. Only the confirmation to overwrite a file (which tries to be close to the normal TA confirmation dialogs with the "safe" option preselected) is a GUI element.  
If the user wants to save a file but the fuzzy search gets in the way the save can be forced (currently via <kbd>Right</kbd>). Inadvertently overwriting a file should not be possible anymore either.

Admittedly I did not test this under MacOS so it's possible that the behavior differs there.

**Pull request closed without merging**
