### PR TITLE
Fix select_directory

### PR DESCRIPTION
**Pull request by loomer**
Slight changes

### CODE REVIEW

**Comment by rgieseke** [comment]
The key seems a simpler way to do it, a Windows fix always be welcome, but the `elseif`block seems to be empty?

**Comment by loomer** [comment]
> but the elseifblock seems to be empty?
Indeed. It gets rid of the trailing '.'
I updated the code, maybe you enjoy this version more.

**Comment by triplejam** [comment]
@loomer  The windows and key changes are fine as far as I know. But I think fixing the directory name should be done in the normalize_dir_path function. Also I think you might be changing the file permissions by accident.

**Comment by rgieseke** [comment]
@triplejam thanks for chiming in, could you give this another look and then i'm happy to merge this!

Thanks @loomer !

**Comment by triplejam** [comment]
@loomer I just tested it and it works fine.

**Comment by rgieseke** [comment]
Awesome! Thanks @triplejam and @loomer

**Pull request merged**
