### PR TITLE
Implementation of select_directory

### PR DESCRIPTION
**Pull request by triplejam**
May need some small changes. Ctrl+d is for when some navigating is still needed. Not sure if using that could cause problems in combination with snapopen.

### CODE REVIEW

**Comment by triplejam** [comment]
If this is good so far, could possibly remove './' from the filter so the currently opened directory could be selected.

**Comment by rgieseke** [comment]
Great! Do you have a usage example?

**Comment by rgieseke** [comment]
That works great! What about using Ctrl-Right-Arrow as a default shortcut for going into a directory?
Ctrl-d closes a buffer in the buffer-list.

**Comment by rgieseke** [comment]
Awesome, is this ready to be merged?

**Comment by triplejam** [comment]
Yes. I think this is good for now. Will implement anything else for it at a later point.

**Comment by rgieseke** [comment]
Great, thanks!

**Pull request merged**
